version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: front-iaframecore:latest
    container_name: front-iaframe-app
    ports:
      - "8080:80"
    environment:
      - API_HOST=http://aa-core.local:8000
      - OPENSEARCH_HOST=http://aa-core.local:9200
      - JWT_SECRET_KEY=jwt_3st_t1c_us3r_k3y
    restart: always